#!/bin/bash

echo "Written to compile a single program file w/o checks though."

#echo "What is the input file name/location?"
#read input

#echo " "$input

#echo "What output name would you like?"
#read output
input="array.c multi-lookup.c util.c";
base="-ggdb -O0 -lpthread -std=gnu99";
output="tester";
xoptions=""; #-Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-parameter";

gcc -Wall -Wextra $xoptions $input $base -o $output

echo "Running output file"
#valgrind -v ./$output
./$output
echo

#echo -e "\nRunning check on kernel with sudo tail /var/log/syslog\n\n"
#sudo tail /var/log/syslog

#echo -e "\nShould see the output for the kernel.\n"

